import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Pacifico, Kanit, Acme, Rammetto_One, Sigmar } from "next/font/google";
import Nav from "@/components/nav/Nav";
import FirebaseCtxProvider from "@/context/firebaseContext";
import GuessGameCtxProvider from "@/context/guessGameContext";
import Slider from "@/components/Slider";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });
const pacifico = Pacifico({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-pacifico",
});
const skranji = Sigmar({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-skranji",
});
const dhurjati = Rammetto_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-dhurjati",
});
const kanit = Kanit({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-kanit",
});
const acme = Acme({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-acme",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${pacifico.variable} ${skranji.variable} ${kanit.variable} ${acme.variable} ${dhurjati.variable} `}
    >
      <FirebaseCtxProvider>
        <GuessGameCtxProvider>
          <body className={inter.className}>
            <Nav />

            {children}
            <Footer />
          </body>
        </GuessGameCtxProvider>
      </FirebaseCtxProvider>
    </html>
  );
}
